"""initial

Revision ID: 463bb4b421f1
Revises: 
Create Date: 2025-12-13 21:43:17.409817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '463bb4b421f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.String(), autoincrement=False, nullable=False),
    sa.Column('creator_id', sa.String(length=10000000000), autoincrement=False, nullable=False),
    sa.Column('video_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('view_count', sa.String(length=10000000000), autoincrement=False, nullable=False),
    sa.Column('likes_count', sa.String(length=10000000000), autoincrement=False, nullable=False),
    sa.Column('reports_count', sa.String(length=10000000000), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creator_id')
    )
    op.create_table('video_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('comments_count', sa.Integer(), nullable=False),
    sa.Column('reports_count', sa.Integer(), nullable=False),
    sa.Column('views_count_delta', sa.Integer(), nullable=False),
    sa.Column('likes_count_delta', sa.Integer(), nullable=False),
    sa.Column('comments_count_delta', sa.Integer(), nullable=False),
    sa.Column('reports_count_delta', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_snapshots')
    op.drop_table('videos')
    # ### end Alembic commands ###
